# Generated by Django 5.2.1 on 2025-05-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0002_stressresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
