# Generated by Django 5.2.1 on 2025-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0003_stressresult_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressresult',
            name='stress_level',
            field=models.CharField(max_length=20),
        ),
    ]
