# Generated by Django 5.2.1 on 2025-05-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0004_sensorreading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
