# Generated by Django 5.2.1 on 2025-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0005_delete_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stressresult',
            name='stress_level',
            field=models.CharField(max_length=20),
        ),
    ]
