# Generated by Django 5.2.1 on 2025-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0002_stressresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
